In [138]:
import math
import numpy as np

In [139]:
def vector_to_matrix(i,j,k,scale_factor):
    P = np.array([i,j,k,0])
    P_scaled = np.array([i,j,k,1])*scale_factor
    lambda_factor = math.sqrt(np.sum(np.square(P)))
    unit_vector = P/lambda_factor
    return print('P Original Vector = {0}\nP Scaled Vector = {1}\nLamda Factor = {2}\nUnity Vector = {3}'.format(P,P_scaled,lambda_factor,unit_vector))

In [140]:
vector_to_matrix(3,5,2,2)

P Original Vector = [3 5 2 0]
P Scaled Vector = [ 6 10  4  2]
Lamda Factor = 6.164414002968976
Unity Vector = [0.48666426 0.81110711 0.32444284 0.        ]


In [141]:
a = np.array([[2,3],[4,5]],dtype=float)
b = np.array([[3,4],[7,8]],dtype=float)
c = np.matmul(a,b)
c

array([[27., 32.],
       [47., 56.]])

In [151]:
from numpy import float16

def translation(F_old,x,y,z):
    Trans = [[1,0,0,x],[0,1,0,y],[0,0,1,z],[0,0,0,1]]
    Trans = np.array(Trans,dtype=float16)
    F_new = np.matmul(Trans,F_old)
    return print('Trans =\n {0}\n\nF_new = Trans x F_old\n {1}\n'.format(Trans,F_new))

In [152]:
F_old = np.array([[0.527,-0.574,0.628,5],[0.369,0.819,0.439,3],[-0.766,0,0.643,8],[0,0,0,1]],dtype=float16)
F_old

array([[ 0.527, -0.574,  0.628,  5.   ],
       [ 0.369,  0.819,  0.439,  3.   ],
       [-0.766,  0.   ,  0.643,  8.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ]], dtype=float16)

In [153]:
translation(F_old,9,0,5)

Trans =
 [[1. 0. 0. 9.]
 [0. 1. 0. 0.]
 [0. 0. 1. 5.]
 [0. 0. 0. 1.]]

F_new = Trans x F_old
 [[ 0.527 -0.574  0.628 14.   ]
 [ 0.369  0.819  0.439  3.   ]
 [-0.766  0.     0.643 13.   ]
 [ 0.     0.     0.     1.   ]]



In [176]:
def rot_x(theta_x):
    Rot_x_theta = np.array([[1,0,0,0],[0,math.cos(theta_x*math.pi/180),-math.sin(theta_x*math.pi/180),0],[0,math.sin(theta_x*math.pi/180),math.cos(theta_x*math.pi/180),0],[0,0,0,1]],dtype=float)
    return Rot_x_theta

In [178]:
def rot_y(theta_y):
    Rot_y_theta = np.array([[math.cos(theta_y*math.pi/180),0,math.sin(theta_y*math.pi/180),0],[0,1,0,0],[-math.sin(theta_y*math.pi/180),0,math.cos(theta_y*math.pi/180),0],[0,0,0,1]],dtype=float)
    return Rot_y_theta
def rot_z(theta_z):
    Rot_z_theta = np.array([[math.cos(theta_z*math.pi/180),-math.sin(theta_z*math.pi/180),0,0],[math.sin(theta_z*math.pi/180),math.cos(theta_z*math.pi/180),0,0],[0,0,1,0],[0,0,0,1]],dtype=float)
    return Rot_z_theta

In [185]:
a = np.array([[2,3],[4,5]])
b = np.array([[4,5],[6,7]])
c = a@b
c

array([[26, 31],
       [46, 55]])

In [195]:
def rotation_transformation_z_y(theta_y,theta_z,Tx,Ty,Tz,n,o,a):
    
    P = np.array([n,o,a,1],dtype=float)

    Trans = [[1,0,0,Tx],[0,1,0,Ty],[0,0,1,Tz],[0,0,0,1]]
    Trans = np.array(Trans,dtype=float16)

    Rot_Y = rot_y(theta_y)
    Rot_Z = rot_z(theta_z)

    R = Rot_Y @ Trans @ Rot_Z @ P
    return print('Trans =\n {0}\n'.format(R))

In [196]:
rotation_transformation_z_y(90,90,4,-3,7,7,3,2)

Trans =
 [ 9.  4. -1.  1.]



In [ ]:
def rotation_transformation_y_z(theta_y,theta_z,Tx,Ty,Tz,n,o,a):
    
    P = np.array([n,o,a,1],dtype=float)

    Trans = [[1,0,0,Tx],[0,1,0,Ty],[0,0,1,Tz],[0,0,0,1]]
    Trans = np.array(Trans,dtype=float16)

    Rot_Y = rot_y(theta_y)
    Rot_Z = rot_z(theta_z)

    R = Rot_Y @ Trans @ Rot_Z @ P
    return print('Trans =\n {0}\n'.format(R))