In [20]:
import numpy as np
import math

### Differential Rotation about a General Axis

In [21]:
def Rot_Theta(del_x,del_y,del_z):
    Rot = np.array([[1,-del_z,del_y,0],[del_z,1,-del_x,0],[-del_y,del_x,1,0],[0,0,0,1]])

    return print('Rot =\n {0}\n'.format(Rot))

In [22]:
Rot_Theta(0.1,0.05,0.002)

Rot =
 [[ 1.    -0.002  0.05   0.   ]
 [ 0.002  1.    -0.1    0.   ]
 [-0.05   0.1    1.     0.   ]
 [ 0.     0.     0.     1.   ]]



### dT = delta x T

### delta = [Trans x Rot - I]

In [23]:
def delta(dx,dy,dz,del_x,del_y,del_z):
    delta = np.array([[0,-del_z,del_y,dx],[del_z,0,-del_x,dy],[-del_y,del_x,0,dz],[0,0,0,0]])
    return delta

In [24]:
delta(0.5,0.3,0.1,0.02,0.04,0.06)

array([[ 0.  , -0.06,  0.04,  0.5 ],
       [ 0.06,  0.  , -0.02,  0.3 ],
       [-0.04,  0.02,  0.  ,  0.1 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ]])

Find the effect of a differential rotation of 0.1 rad about the y-axis followed by a differential translation of [0.1,0,0.2] on the given frame B

B =[
    0 0 1 10,
    1 0 0 5,
    0 1 0 3,
    0 0 0 1
    ]


In [36]:
def delta_B(dx,dy,dz,del_x,del_y,del_z,B):
    delta_op = delta(dx,dy,dz,del_x,del_y,del_z)
    del_B = delta_op @ B
    B_new = B + del_B
    return print('dB =\n {0}\n B_new = \n{1}'.format(del_B,B_new))

In [37]:
B = np.array([[0,0,1,10],[1,0,0,5],[0,1,0,3],[0,0,0,1]],dtype=float)
delta_B(0.1,0,0.2,0,0.1,0,B)

dB =
 [[ 0.   0.1  0.   0.4]
 [ 0.   0.   0.   0. ]
 [ 0.   0.  -0.1 -0.8]
 [ 0.   0.   0.   0. ]]
 B_new = 
[[ 0.   0.1  1.  10.4]
 [ 1.   0.   0.   5. ]
 [ 0.   1.  -0.1  2.2]
 [ 0.   0.   0.   1. ]]
